---
title: "Emotionality influences beliefs_Final Analysis"
author: "Salonee Jukar & Matti Vuorre"
date: "2025-05-01"
output: pdf_document
---

```{r}
rm(list = ls())
```


```{r setup, include=FALSE}
# Load required libraries
#install.packages("")
library(psych)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)
library(tidyverse)
library(httr)
library(Matrix)
library(lmerTest) 
library(lme4)
library(nnet)
library(reshape2)
library(Hmisc)
library(car)
```

```{r}
# Read the CSV file with the appropriate delimiter
column_names<-names(read.csv(file.choose(), nrows = 1))
data<-read.csv(file.choose(), sep=",", skip = 128, header = FALSE)
names(data) <- column_names

View(data) #check if the loaded data looks correct
```


```{r}
#per participant CRT score
table(data$CRT1_1)
table(data$CRT1_2)
table(data$CRT1_3)
table(data$CRT3_1)
table(data$CRT3_2)
table(data$CRT3_3)
score_1 <-ifelse(data$CRT1_1 == 4, 1, 0)
score_2 <-ifelse(data$CRT1_2 == 10, 1, 0)
score_3 <-ifelse(data$CRT1_3 == 39, 1, 0)
score_4 <-ifelse(data$CRT3_1 == 2, 1, 0)
score_5 <-ifelse(data$CRT3_2 == 8, 1, 0)
score_6 <- ifelse(tolower(trimws(data$CRT3_3)) == "emily", 1, 0)

scores<-data.frame(score_1, score_2, score_3, score_4, score_5, score_6)
data$CRT_score<-rowSums(scores) #added the CRT total for each participant in the data

#divide 2 data sets per Series (A and B)
data_A <- subset(data, Series == "A")
data_B <- subset(data, Series == "B")

```

```{r}
#Clean data --> longform for the analysis
column_headers<- names(participant_id, headline_code, emotionality, veracity, belief, age, gender, political_orientation, series, emotionality_rating, CRT)

participant_id <- rep(1:105, each = 16)

#headline codes
grp1 <- rep(c("T1E","T2E","T3E","T4E","T5N","T6N","T7N","T8N",
    "F1E","F2E","F3E","F4E","F5N","F6N","F7N","F8N"),
  times = 53)

grp2 <- rep(c("T1N","T2N","T3N","T4N","T5E","T6E","T7E","T8E",
    "F1N","F2N","F3N","F4N","F5E","F6E","F7E","F8E"),
  times = 52)
# Combine into one column
headline_code<- c(grp1, grp2)

#headline emotionality (manipulated)
grp1_emo <- rep(c(1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0), times = 53)
grp2_emo <- rep(c(0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1), times = 52)
emotionality<-c(grp1_emo, grp2_emo)

#headline veracity (manipulated)
veracity <- rep(c(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0), times = 105)

#age per participant
age_1<-rep(data_A$Age_1, each = 16)
age_2<-rep(data_B$Age_1, each = 16)
age<-c(age_1, age_2)

#gender per participant
gender_1<-rep(data_A$Gender, each = 16)
gender_2<-rep(data_B$Gender, each = 16)
gender<-c(gender_1, gender_2)

#political orientation per participant
po_1<-rep(data_A$Pol..partisanship._1, each = 16)
po_2<-rep(data_B$Pol..partisanship._1, each = 16)
political_orientation<-c(po_1, po_2)

#CRT per participant
crt_1<-rep(data_A$CRT_score, each = 16)
crt_2<-rep(data_B$CRT_score, each=16)
CRT<-c(crt_1, crt_2)

#Belief per participant
belief_1 <- as.vector(t(data_A[, 19:34]))
belief_2 <- as.vector(t(data_B[, 51:66]))
belief<-c(belief_1, belief_2)


#Emotionality rating
emorating_1<-as.vector(t(data_A[,35:50]))
emorating_2 <- as.vector(t(data_B[, 67:82]))
emotionality_rating<-c(emorating_1, emorating_2)


#group categorisation (Series A/B)
series <- c(rep("A", length(grp1)), rep("B", length(grp2)))

rm(grp1, grp2, grp1_emo, grp2_emo, age_1, age_2, gender_1, gender_2, po_1, po_2, crt_1, crt_2, belief_1, belief_2, emorating_1, emorating_2)#removing unnecessary variables from the environment

#Creating a final data set 
data_n<-data.frame(participant_id, headline_code, emotionality, veracity, belief, emotionality_rating, CRT, series, age, gender, political_orientation)

View(data_n)
```

```{r}
#manipulation check
mani_emo <- lm(emotionality_rating ~ emotionality, data = data_n)
summary(mani_emo)

mani_ver <- lm(emotionality_rating ~ veracity, data = data_n)
summary(mani_ver)
```

```{r}
#Main analysis
model= lmerTest::lmer(belief ~ emotionality*veracity*CRT+ (1 + emotionality+veracity|participant_id) +(1|headline_code), data=data_n, na.action=na.omit)
summary(model)  
fixef(model) #only extracting the fixed-effects estimates
confint(model) #confidence intervals for the fixed-effects estimates

#Moderation graphs




```

```{r}
model_glmm <- glmer(
  belief ~ emotionality * veracity * CRT +
    (1 + emotionality + veracity | participant_id) +
    (1 | headline_code),
  data = data_n,
  family = poisson(link = "log"),
  na.action = na.omit,
  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5))
)


summary(model_glmm)
```


```{r}
#Additional analysis and assumption checks 
# Residuals vs. fitted values
plot(model) 

# Q-Q plot for residuals
qqnorm(resid(model))
qqline(resid(model))

```
